#!/usr/bin/env python3
"""Generate the immutable Windows/CLDR lookup; Python is a build-time tool only."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import struct
import xml.etree.ElementTree as ET

TZ_FILES = ("africa", "antarctica", "asia", "australasia", "europe",
            "northamerica", "southamerica", "etcetera", "factory",
            "backward", "backzone")
ID = re.compile(r"[A-Za-z0-9_+.-]+(?:/[A-Za-z0-9_+.-]+)*\Z")
TERRITORY = re.compile(r"(?:001|[A-Z]{2})\Z")


def tz_identifiers(directory, pin):
    """Validate the pinned Zone/Link inputs and collect primary names and aliases."""
    names = set()
    for name in TZ_FILES:
        data = (Path(directory) / name).read_bytes()
        if hashlib.sha256(data).hexdigest() != pin["files"][name]:
            raise ValueError("tz source hash mismatch: " + name)
        for line in data.decode("utf-8").splitlines():
            fields = line.split("#", 1)[0].split()
            if fields and fields[0] == "Zone" and len(fields) >= 2:
                names.add(fields[1])
            elif fields and fields[0] == "Link" and len(fields) >= 3:
                names.add(fields[2])
    return names


def parse_mapping(data, available):
    root = ET.fromstring(data)
    maps = root.findall("./windowsZones/mapTimezones")
    if root.tag != "supplementalData" or len(maps) != 1:
        raise ValueError("expected one windowsZones/mapTimezones")
    groups = {}
    originals = {}
    for entry in maps[0]:
        if entry.tag != "mapZone" or set(entry.attrib) != {"other", "territory", "type"}:
            raise ValueError("malformed mapZone")
        key, territory = entry.attrib["other"], entry.attrib["territory"]
        if not 1 <= len(key) <= 127 or any(not 32 <= ord(c) <= 126 for c in key):
            raise ValueError("invalid Windows key")
        if key != key.strip() or not TERRITORY.fullmatch(territory):
            raise ValueError("invalid key or territory")
        folded = key.lower()
        if folded in originals and originals[folded] != key:
            raise ValueError("Windows keys collide under ASCII case folding")
        originals[folded] = key
        targets = entry.attrib["type"].split()
        if not targets or len(set(targets)) != len(targets):
            raise ValueError("empty or duplicate target list")
        for target in targets:
            if not ID.fullmatch(target) or any(p in (".", "..") for p in target.split("/")):
                raise ValueError("invalid IANA identifier: " + target)
            if target not in available:
                raise ValueError("IANA identifier absent from pinned tz: " + target)
        rows = groups.setdefault(folded, {})
        if territory in rows:
            raise ValueError("duplicate Windows key/territory: " + key + "/" + territory)
        rows[territory] = tuple(targets)  # CLDR order is significant.
    if not groups or any("001" not in rows for rows in groups.values()):
        raise ValueError("each Windows key requires its 001 mapping")
    return groups


def encode(groups):
    """WTZ1: 16-byte LE header, 8-byte keys, 8-byte rows, interned ASCII pool."""
    total_rows = sum(len(rows) for rows in groups.values())
    if len(groups) > 65535 or total_rows > 65535:
        raise ValueError("record count exceeds format limit")
    pool = bytearray()
    offsets = {}

    def intern(text):
        if text not in offsets:
            offsets[text] = len(pool)
            pool.extend(text.encode("ascii") + b"\0")
        if len(pool) > 65535:
            raise ValueError("string pool exceeds format limit")
        return offsets[text]

    keys, rows = bytearray(), bytearray()
    row_count = 0
    for key, territories in sorted(groups.items()):
        keys.extend(struct.pack("<HHHH", intern(key), row_count, len(territories), 0))
        for territory, targets in sorted(territories.items()):
            text = " ".join(targets)
            if len(text) > 65535:
                raise ValueError("target list exceeds format limit")
            code = territory.encode("ascii").ljust(3, b"\0")
            rows.extend(code + b"\0" + struct.pack("<HH", intern(text), len(text)))
            row_count += 1
    strings_at = 16 + len(keys) + len(rows)
    header = struct.pack("<4sIHHI", b"WTZ1", strings_at + len(pool), len(groups),
                         row_count, strings_at)
    return header + keys + rows + pool


def render(blob, cldr_pin, tz_pin):
    lines = ["/* Generated by tools/gen-windows-zones.py; do not edit.",
             " * Derived from Unicode CLDR windowsZones.xml (UNICODE LICENSE V3).",
             " * See tools/timezone/cldr/LICENSE for the copyright and permission notice.",
             " * CLDR commit: " + cldr_pin["commit"],
             " * CLDR date: " + cldr_pin["date"],
             " * XML SHA-256: " + cldr_pin["xml_sha256"],
             " * tz commit: " + tz_pin["commit"],
             " * Binary SHA-256: " + hashlib.sha256(blob).hexdigest(),
             " */", "static const unsigned char qjs_windows_zone_data[] = {"]
    for pos in range(0, len(blob), 12):
        lines.append("    " + ", ".join("0x%02x" % b for b in blob[pos:pos + 12]) + ",")
    return "\n".join(lines + ["};", ""])


def generate(xml, cldr_pin, tz_source, tz_pin):
    if hashlib.sha256(xml).hexdigest() != cldr_pin["xml_sha256"]:
        raise ValueError("CLDR XML hash mismatch")
    groups = parse_mapping(xml, tz_identifiers(tz_source, tz_pin))
    return render(encode(groups), cldr_pin, tz_pin)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--xml", type=Path, required=True)
    parser.add_argument("--cldr-pin", type=Path, required=True)
    parser.add_argument("--tz-source", type=Path, required=True)
    parser.add_argument("--tz-pin", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        content = generate(args.xml.read_bytes(), json.loads(args.cldr_pin.read_text()),
                           args.tz_source, json.loads(args.tz_pin.read_text()))
    except (ValueError, KeyError, OSError, ET.ParseError) as error:
        parser.error(str(error))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="ascii", newline="\n") as stream:
        stream.write(content)


if __name__ == "__main__":
    main()
